@Enpal.DaprMachineFactory.Workers_HostAddress = http://localhost:5253
@id = my_favorite_workflow
###

POST {{Enpal.DaprMachineFactory.Workers_HostAddress}}/startWorkflow/{{id}}
Accept: application/json
Content-Type: application/json
###

POST {{Enpal.DaprMachineFactory.Workers_HostAddress}}/stopWorkflow/{{id}}
Accept: application/json
Content-Type: application/json
###

POST {{Enpal.DaprMachineFactory.Workers_HostAddress}}/getWorkflowStatus/{{id}}
Accept: application/json
Content-Type: application/json
###