apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pg.statestore
spec:
  type: state.postgresql
  version: v2
  metadata:
    - name: connectionString
      value: "postgresql://localhost:5542?user=postgres&password=password"
    - name: actorStateStore
      value: "true"